FROM odoo:17.0

USER root

# 1. Install MS SQL ODBC Driver
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gnupg2 \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y --no-install-recommends \
    msodbcsql17 \
    unixodbc-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 2. Python lib installation
RUN pip3 install pyodbc

USER odoo